  ServerAdmin   dan@langille.org

  SetEnvIf Remote_Addr "127\.0\.0\.1" dontlog
  SetEnvIf User-Agent ".*internal dummy connection.*" dontlog

  DocumentRoot  /usr/websites/api.freshports.org/www
  ServerName    api.freshports.org

  ErrorLog      /usr/websites/log/api.freshports.org-error.log
  CustomLog     /usr/websites/log/api.freshports.org-access.log combined env=!dontlog

  RewriteLog    /usr/websites/log/freshports.org-rewrite.log

  <Directory    /usr/websites/api.freshports.org/www>
    AllowOverride None
    Order deny,allow
    Allow from all
  </Directory>
