  ServerAdmin   dan@langille.org

  DocumentRoot  /usr/websites/api.freshports.org
  ServerName    api.freshports.org

  ErrorLog      /usr/websites/log/api.freshports.org-error.log
  CustomLog     /usr/websites/log/api.freshports.org-access.log combined

  RewriteLog    /usr/websites/log/freshports.org-rewrite.log

  <Directory    /usr/websites/api.freshports.org/www>
    AllowOverride None
    Order deny,allow
    Allow from all
  </Directory>
